openapi: 3.0.0
info:
  title: GitHub Repository Analyzer and Authentication Service
  version: 1.0.0
  description: Services for analyzing GitHub repositories and handling OAuth authentication.
servers:
  - url: https://gcb-ts.onrender.com/api
paths:
  /auth/github:
    get:
      operationId: initiateGithubAuthentication
      summary: Initiates GitHub OAuth authentication flow.
      responses:
        "302":
          description: Redirect to GitHub for authentication.
        "500":
          description: Internal server error.
  /auth/github/callback:
    get:
      operationId: githubCallback
      summary: Callback endpoint for GitHub OAuth flow.
      responses:
        "302":
          description: Redirect to OpenAI callback URL with state and code.
        "500":
          description: Internal server error.
  /auth/github/token:
    post:
      operationId: exchangeGithubToken
      summary: Exchange the authorization code for an access token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: GitHub authorization code.
              required:
                - code
      responses:
        "200":
          description: Access token exchanged successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: e72e16c7e42f292c6912e7710c838347ae178b4a
        "400":
          description: Bad request.
        "500":
          description: Internal server error.
  /repo/analyze:
    post:
      operationId: analyzeGithubRepository
      summary: Analyzes a specified GitHub repository URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                githubUrl:
                  type: string
                  description: The URL of the GitHub repository to analyze.
              required:
                - githubUrl
      responses:
        "200":
          description: Repository analysis completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis:
                    type: string
                    description: Summary of the repository analysis.
                  repoDetails:
                    type: object
                    description: Detailed information about the repository.
        "400":
          description: Bad request.
        "401":
          description: Unauthorized access, requires user authentication.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating the need for user authentication.
                  authUrl:
                    type: string
                    description: URL to redirect to for GitHub OAuth authentication.
        "404":
          description: Repository not found or access denied.
        "500":
          description: Internal server error.
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message detailing the reason for the failure.
